vich_uploader:
    db_driver: orm

    mappings:
        articles:
            uri_prefix: /images/articles
            upload_destination: '%kernel.project_dir%/public/images/articles'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        courses:
            uri_prefix: /upload/courses
            upload_destination: '%kernel.project_dir%/public/upload/courses'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer